import type {
  AdminUser,
  Role,
  Permission,
  ApprovalRequest,
  TransactionMonitor,
  VillageManagement,
  AuditLog,
  WebContent,
} from "@/types";

// ============================================================
// MOCK USERS
// ============================================================
export const mockUsers: AdminUser[] = [
  {
    id: "u1",
    email: "superadmin@dewi.id",
    name: "Budi Santoso",
    phone: "081234567890",
    role: "super_admin",
    status: "active",
    isApproved: true,
    emailVerified: true,
    lastLoginAt: "2026-04-11T08:30:00Z",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2026-04-11T08:30:00Z",
  },
  {
    id: "u2",
    email: "admin@desawisata.id",
    name: "Siti Rahayu",
    phone: "081234567891",
    role: "admin",
    status: "active",
    isApproved: true,
    emailVerified: true,
    lastLoginAt: "2026-04-10T14:00:00Z",
    createdAt: "2025-02-15T00:00:00Z",
    updatedAt: "2026-04-10T14:00:00Z",
  },
  {
    id: "u3",
    email: "finance@dewi.id",
    name: "Ahmad Wijaya",
    phone: "081234567892",
    role: "finance_admin",
    status: "active",
    isApproved: true,
    emailVerified: true,
    lastLoginAt: "2026-04-09T09:00:00Z",
    createdAt: "2025-03-01T00:00:00Z",
    updatedAt: "2026-04-09T09:00:00Z",
  },
  {
    id: "u4",
    email: "support@dewi.id",
    name: "Dewi Lestari",
    phone: "081234567893",
    role: "support",
    status: "active",
    isApproved: true,
    emailVerified: true,
    lastLoginAt: "2026-04-11T07:00:00Z",
    createdAt: "2025-04-01T00:00:00Z",
    updatedAt: "2026-04-11T07:00:00Z",
  },
  {
    id: "u5",
    email: "hotel@dewi.id",
    name: "Pak Wayan",
    phone: "081234567894",
    role: "viewer",
    partnerRole: "ACCOMMODATION",
    villageId: "v1",
    villageName: "Desa Penglipuran",
    status: "active",
    isApproved: true,
    emailVerified: true,
    lastLoginAt: "2026-04-08T16:00:00Z",
    createdAt: "2025-05-10T00:00:00Z",
    updatedAt: "2026-04-08T16:00:00Z",
  },
  {
    id: "u6",
    email: "umkm@dewi.id",
    name: "Ibu Ketut",
    phone: "081234567895",
    role: "viewer",
    partnerRole: "UMKM",
    villageId: "v1",
    villageName: "Desa Penglipuran",
    status: "active",
    isApproved: true,
    emailVerified: true,
    lastLoginAt: "2026-04-07T10:00:00Z",
    createdAt: "2025-06-01T00:00:00Z",
    updatedAt: "2026-04-07T10:00:00Z",
  },
  {
    id: "u7",
    email: "event@dewi.id",
    name: "Made Surya",
    phone: "081234567896",
    role: "viewer",
    partnerRole: "EVENT_ORGANIZER",
    villageId: "v2",
    villageName: "Desa Wae Rebo",
    status: "pending_verification",
    isApproved: false,
    emailVerified: true,
    createdAt: "2026-04-01T00:00:00Z",
    updatedAt: "2026-04-01T00:00:00Z",
  },
  {
    id: "u8",
    email: "admin.village@dewi.id",
    name: "Nyoman Adi",
    phone: "081234567897",
    role: "viewer",
    partnerRole: "VILLAGE_ADMIN",
    villageId: "v3",
    villageName: "Desa Nglanggeran",
    status: "suspended",
    isApproved: true,
    emailVerified: true,
    lastLoginAt: "2026-03-15T12:00:00Z",
    createdAt: "2025-07-15T00:00:00Z",
    updatedAt: "2026-03-20T00:00:00Z",
  },
  {
    id: "u9",
    email: "viewer@dewi.id",
    name: "Rina Kartika",
    role: "viewer",
    status: "active",
    isApproved: true,
    emailVerified: true,
    lastLoginAt: "2026-04-10T11:00:00Z",
    createdAt: "2025-08-01T00:00:00Z",
    updatedAt: "2026-04-10T11:00:00Z",
  },
  {
    id: "u10",
    email: "new.partner@dewi.id",
    name: "Gede Putra",
    phone: "081234567899",
    role: "viewer",
    partnerRole: "ACCOMMODATION",
    villageId: "v2",
    villageName: "Desa Wae Rebo",
    status: "pending_verification",
    isApproved: false,
    emailVerified: false,
    createdAt: "2026-04-10T00:00:00Z",
    updatedAt: "2026-04-10T00:00:00Z",
  },
];

// ============================================================
// MOCK ROLES & PERMISSIONS
// ============================================================
const allActions: Permission["actions"] = ["view", "create", "update", "delete", "export", "approve"];
const viewOnly: Permission["actions"] = ["view"];

export const defaultPermissions: Record<string, Permission[]> = {
  super_admin: [
    { module: "users", actions: allActions },
    { module: "roles", actions: allActions },
    { module: "villages", actions: allActions },
    { module: "approvals", actions: allActions },
    { module: "transactions", actions: allActions },
    { module: "audit_logs", actions: viewOnly },
    { module: "settings", actions: allActions },
    { module: "dashboard", actions: viewOnly },
    { module: "content", actions: allActions },
  ],
  admin: [
    { module: "users", actions: allActions },
    { module: "roles", actions: [] },
    { module: "villages", actions: allActions },
    { module: "approvals", actions: allActions },
    { module: "transactions", actions: viewOnly },
    { module: "audit_logs", actions: viewOnly },
    { module: "settings", actions: [] },
    { module: "dashboard", actions: viewOnly },
    { module: "content", actions: allActions },
  ],
  finance_admin: [
    { module: "users", actions: [] },
    { module: "roles", actions: [] },
    { module: "villages", actions: viewOnly },
    { module: "approvals", actions: [] },
    { module: "transactions", actions: allActions },
    { module: "audit_logs", actions: viewOnly },
    { module: "settings", actions: [] },
    { module: "dashboard", actions: viewOnly },
    { module: "content", actions: [] },
  ],
  support: [
    { module: "users", actions: viewOnly },
    { module: "roles", actions: [] },
    { module: "villages", actions: viewOnly },
    { module: "approvals", actions: viewOnly },
    { module: "transactions", actions: viewOnly },
    { module: "audit_logs", actions: viewOnly },
    { module: "settings", actions: [] },
    { module: "dashboard", actions: viewOnly },
    { module: "content", actions: [] },
  ],
  viewer: [
    { module: "users", actions: viewOnly },
    { module: "roles", actions: [] },
    { module: "villages", actions: viewOnly },
    { module: "approvals", actions: viewOnly },
    { module: "transactions", actions: viewOnly },
    { module: "audit_logs", actions: [] },
    { module: "settings", actions: [] },
    { module: "dashboard", actions: viewOnly },
    { module: "content", actions: [] },
  ],
};

export const mockRoles: Role[] = [
  {
    id: "r1",
    name: "Super Admin",
    slug: "super_admin",
    description: "Akses penuh ke seluruh fitur platform",
    permissions: defaultPermissions.super_admin,
    userCount: 1,
    isSystem: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "r2",
    name: "Admin",
    slug: "admin",
    description: "Kelola user, desa, approval, dan konten",
    permissions: defaultPermissions.admin,
    userCount: 1,
    isSystem: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "r3",
    name: "Finance Admin",
    slug: "finance_admin",
    description: "Kelola transaksi dan settlement",
    permissions: defaultPermissions.finance_admin,
    userCount: 1,
    isSystem: false,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "r4",
    name: "Support",
    slug: "support",
    description: "Lihat data dan bantu partner",
    permissions: defaultPermissions.support,
    userCount: 1,
    isSystem: false,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "r5",
    name: "Viewer",
    slug: "viewer",
    description: "Hanya bisa melihat data (read-only)",
    permissions: defaultPermissions.viewer,
    userCount: 5,
    isSystem: false,
    createdAt: "2025-01-01T00:00:00Z",
  },
];

// ============================================================
// MOCK VILLAGES
// ============================================================
export const mockVillages: VillageManagement[] = [
  {
    id: "v1",
    name: "Desa Penglipuran",
    slug: "penglipuran",
    address: "Jl. Penglipuran, Kubu, Bangli",
    province: "Bali",
    regency: "Bangli",
    district: "Kubu",
    latitude: -8.4226,
    longitude: 115.3572,
    description: "Desa adat yang terkenal dengan keindahan arsitektur tradisional Bali.",
    history: "Desa Penglipuran telah ada sejak abad ke-13...",
    contact: {
      phone: "036291234",
      email: "info@penglipuran.id",
      website: "https://penglipuran.id",
      socialMedia: { instagram: "@penglipuran", facebook: "Penglipuran Village" },
    },
    gallery: ["/images/penglipuran-1.jpg", "/images/penglipuran-2.jpg"],
    bankInfo: { bankName: "BPD Bali", accountNumber: "123456789", accountHolder: "Desa Adat Penglipuran" },
    governmentServices: [
      { type: "clinic", name: "Puskesmas Kubu I", phone: "036291111", address: "Jl. Raya Kubu", isPriority: true },
      { type: "police", name: "Polsek Kubu", phone: "036291222", address: "Jl. Raya Kubu", isPriority: false },
    ],
    status: "active",
    verifiedAt: "2025-02-01T00:00:00Z",
    stats: {
      totalPartners: 12,
      totalFacilities: 8,
      totalExperiences: 15,
      monthlyRevenue: 45600000,
      averageRating: 4.8,
    },
    createdAt: "2025-01-15T00:00:00Z",
    updatedAt: "2026-04-10T00:00:00Z",
  },
  {
    id: "v2",
    name: "Desa Wae Rebo",
    slug: "wae-rebo",
    address: "Desa Todo, Satarmese Barat, Manggarai",
    province: "Nusa Tenggara Timur",
    regency: "Manggarai",
    district: "Satarmese Barat",
    latitude: -8.7714,
    longitude: 120.3044,
    description: "Desa adat di ketinggian 1.100 mdpl dengan rumah adat Mbaru Niang.",
    contact: { phone: "081339123456", email: "info@waerebo.id" },
    gallery: ["/images/waerebo-1.jpg"],
    governmentServices: [
      { type: "clinic", name: "Puskesmas Todo", phone: "081339111222", address: "Desa Todo", isPriority: true },
    ],
    status: "active",
    verifiedAt: "2025-03-15T00:00:00Z",
    stats: {
      totalPartners: 6,
      totalFacilities: 3,
      totalExperiences: 8,
      monthlyRevenue: 28000000,
      averageRating: 4.9,
    },
    createdAt: "2025-03-01T00:00:00Z",
    updatedAt: "2026-04-08T00:00:00Z",
  },
  {
    id: "v3",
    name: "Desa Nglanggeran",
    slug: "nglanggeran",
    address: "Nglanggeran, Patuk, Gunungkidul",
    province: "DI Yogyakarta",
    regency: "Gunungkidul",
    district: "Patuk",
    latitude: -7.8475,
    longitude: 110.5154,
    description: "Desa wisata dengan Gunung Api Purba dan embung alam.",
    contact: { phone: "027412345", email: "info@nglanggeran.id" },
    gallery: [],
    governmentServices: [],
    status: "active",
    verifiedAt: "2025-04-01T00:00:00Z",
    stats: {
      totalPartners: 9,
      totalFacilities: 5,
      totalExperiences: 12,
      monthlyRevenue: 35000000,
      averageRating: 4.6,
    },
    createdAt: "2025-04-01T00:00:00Z",
    updatedAt: "2026-04-05T00:00:00Z",
  },
  {
    id: "v4",
    name: "Desa Pentingsari",
    slug: "pentingsari",
    address: "Pentingsari, Umbulharjo, Cangkringan, Sleman",
    province: "DI Yogyakarta",
    regency: "Sleman",
    district: "Cangkringan",
    latitude: -7.6045,
    longitude: 110.4420,
    description: "Desa wisata edukatif di lereng Gunung Merapi.",
    contact: { phone: "027498765", email: "info@pentingsari.id" },
    gallery: [],
    governmentServices: [],
    status: "pending",
    stats: {
      totalPartners: 0,
      totalFacilities: 0,
      totalExperiences: 0,
      monthlyRevenue: 0,
      averageRating: 0,
    },
    createdAt: "2026-04-05T00:00:00Z",
    updatedAt: "2026-04-05T00:00:00Z",
  },
  {
    id: "v5",
    name: "Desa Pujon Kidul",
    slug: "pujon-kidul",
    address: "Pujon Kidul, Pujon, Malang",
    province: "Jawa Timur",
    regency: "Malang",
    district: "Pujon",
    latitude: -7.8934,
    longitude: 112.4351,
    description: "Desa wisata dengan cafe sawah dan edukasi pertanian.",
    contact: { phone: "034112345", email: "info@pujonkidul.id" },
    gallery: [],
    governmentServices: [],
    status: "suspended",
    stats: {
      totalPartners: 4,
      totalFacilities: 2,
      totalExperiences: 5,
      monthlyRevenue: 0,
      averageRating: 4.2,
    },
    createdAt: "2025-06-01T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z",
  },
];

// ============================================================
// MOCK APPROVALS
// ============================================================
export const mockApprovals: ApprovalRequest[] = [
  {
    id: "a1",
    type: "partner_registration",
    applicant: { userId: "u10", name: "Gede Putra", email: "new.partner@dewi.id", phone: "081234567899" },
    villageId: "v2",
    villageName: "Desa Wae Rebo",
    partnerRole: "ACCOMMODATION",
    status: "pending",
    completionScore: 75,
    checklist: { businessInfo: true, documents: true, location: true, financial: false, media: false },
    documents: [
      { id: "d1", name: "KTP.pdf", type: "identity", url: "/docs/ktp.pdf", uploadedAt: "2026-04-10T00:00:00Z" },
      { id: "d2", name: "SIUP.pdf", type: "business", url: "/docs/siup.pdf", uploadedAt: "2026-04-10T00:00:00Z" },
    ],
    submittedAt: "2026-04-10T08:00:00Z",
  },
  {
    id: "a2",
    type: "partner_registration",
    applicant: { userId: "u7", name: "Made Surya", email: "event@dewi.id", phone: "081234567896" },
    villageId: "v2",
    villageName: "Desa Wae Rebo",
    partnerRole: "EVENT_ORGANIZER",
    status: "under_review",
    completionScore: 90,
    checklist: { businessInfo: true, documents: true, location: true, financial: true, media: false },
    documents: [
      { id: "d3", name: "KTP.pdf", type: "identity", url: "/docs/ktp2.pdf", uploadedAt: "2026-04-01T00:00:00Z" },
      { id: "d4", name: "Portfolio.pdf", type: "business", url: "/docs/portfolio.pdf", uploadedAt: "2026-04-01T00:00:00Z" },
    ],
    reviewedBy: "u2",
    submittedAt: "2026-04-01T10:00:00Z",
  },
  {
    id: "a3",
    type: "village_registration",
    applicant: { userId: "u8", name: "Nyoman Adi", email: "admin.village@dewi.id", phone: "081234567897" },
    villageName: "Desa Pentingsari",
    partnerRole: "VILLAGE_ADMIN",
    status: "pending",
    completionScore: 60,
    checklist: { businessInfo: true, documents: false, location: true, financial: false, media: false },
    documents: [
      { id: "d5", name: "SK_Kepala_Desa.pdf", type: "official", url: "/docs/sk.pdf", uploadedAt: "2026-04-05T00:00:00Z" },
    ],
    submittedAt: "2026-04-05T14:00:00Z",
  },
  {
    id: "a4",
    type: "accommodation_submission",
    applicant: { userId: "u5", name: "Pak Wayan", email: "hotel@dewi.id", phone: "081234567894" },
    villageId: "v1",
    villageName: "Desa Penglipuran",
    partnerRole: "ACCOMMODATION",
    status: "approved",
    completionScore: 100,
    checklist: { businessInfo: true, documents: true, location: true, financial: true, media: true },
    documents: [
      { id: "d6", name: "Foto_Properti.zip", type: "media", url: "/docs/photos.zip", uploadedAt: "2026-03-20T00:00:00Z" },
    ],
    reviewedBy: "u1",
    reviewNotes: "Semua dokumen lengkap dan valid.",
    submittedAt: "2026-03-15T09:00:00Z",
    reviewedAt: "2026-03-20T15:00:00Z",
  },
  {
    id: "a5",
    type: "withdrawal_request",
    applicant: { userId: "u6", name: "Ibu Ketut", email: "umkm@dewi.id", phone: "081234567895" },
    villageId: "v1",
    villageName: "Desa Penglipuran",
    partnerRole: "UMKM",
    status: "rejected",
    completionScore: 100,
    checklist: { businessInfo: true, documents: true, location: true, financial: true, media: true },
    documents: [],
    reviewedBy: "u3",
    reviewNotes: "Saldo belum mencapai minimum pencairan.",
    submittedAt: "2026-03-28T11:00:00Z",
    reviewedAt: "2026-03-29T09:00:00Z",
  },
  {
    id: "a6",
    type: "partner_registration",
    applicant: { userId: "u11", name: "Kadek Ari", email: "kadek@dewi.id", phone: "081234567801" },
    villageId: "v1",
    villageName: "Desa Penglipuran",
    partnerRole: "UMKM",
    status: "revision_required",
    completionScore: 50,
    checklist: { businessInfo: true, documents: false, location: true, financial: false, media: false },
    documents: [
      { id: "d7", name: "KTP.pdf", type: "identity", url: "/docs/ktp3.pdf", uploadedAt: "2026-04-02T00:00:00Z" },
    ],
    reviewedBy: "u2",
    reviewNotes: "Dokumen SIUP belum dilampirkan. Mohon lengkapi dokumen bisnis.",
    submittedAt: "2026-04-02T08:00:00Z",
    reviewedAt: "2026-04-03T10:00:00Z",
  },
];

// ============================================================
// MOCK TRANSACTIONS
// ============================================================
export const mockTransactions: TransactionMonitor[] = [
  {
    id: "t1",
    orderId: "ORD-2026-0001",
    type: "accommodation",
    status: "success",
    amount: 1500000,
    currency: "IDR",
    platformFee: 225000,
    paymentMethod: "va_bca",
    paymentProvider: "midtrans",
    buyerUserId: "b1",
    buyerName: "Andi Pratama",
    partnerUserId: "u5",
    partnerName: "Pak Wayan",
    villageId: "v1",
    villageName: "Desa Penglipuran",
    splits: [
      { recipientType: "partner", recipientId: "u5", recipientName: "Pak Wayan", amount: 1275000, percentage: 85 },
      { recipientType: "platform", recipientId: "platform", recipientName: "Admin DeWi", amount: 225000, percentage: 15 },
    ],
    settlement: { status: "completed", schedule: "standard", completedAt: "2026-04-08T00:00:00Z" },
    createdAt: "2026-04-01T10:30:00Z",
    updatedAt: "2026-04-08T00:00:00Z",
  },
  {
    id: "t2",
    orderId: "ORD-2026-0002",
    type: "sme_order",
    status: "success",
    amount: 250000,
    currency: "IDR",
    platformFee: 25000,
    paymentMethod: "ewallet_gopay",
    paymentProvider: "midtrans",
    buyerUserId: "b2",
    buyerName: "Rini Susanti",
    partnerUserId: "u6",
    partnerName: "Ibu Ketut",
    villageId: "v1",
    villageName: "Desa Penglipuran",
    splits: [
      { recipientType: "partner", recipientId: "u6", recipientName: "Ibu Ketut", amount: 225000, percentage: 90 },
      { recipientType: "platform", recipientId: "platform", recipientName: "Admin DeWi", amount: 25000, percentage: 10 },
    ],
    settlement: { status: "completed", schedule: "standard", completedAt: "2026-04-09T00:00:00Z" },
    createdAt: "2026-04-02T14:00:00Z",
    updatedAt: "2026-04-09T00:00:00Z",
  },
  {
    id: "t3",
    orderId: "ORD-2026-0003",
    type: "experience",
    status: "pending",
    amount: 750000,
    currency: "IDR",
    platformFee: 112500,
    paymentMethod: "qris",
    paymentProvider: "midtrans",
    buyerUserId: "b3",
    buyerName: "Joko Widodo",
    partnerUserId: "u7",
    partnerName: "Made Surya",
    villageId: "v2",
    villageName: "Desa Wae Rebo",
    splits: [
      { recipientType: "partner", recipientId: "u7", recipientName: "Made Surya", amount: 637500, percentage: 85 },
      { recipientType: "platform", recipientId: "platform", recipientName: "Admin DeWi", amount: 112500, percentage: 15 },
    ],
    createdAt: "2026-04-11T08:00:00Z",
    updatedAt: "2026-04-11T08:00:00Z",
  },
  {
    id: "t4",
    orderId: "ORD-2026-0004",
    type: "accommodation",
    status: "refunded",
    amount: 2000000,
    currency: "IDR",
    platformFee: 300000,
    paymentMethod: "va_mandiri",
    paymentProvider: "xendit",
    buyerUserId: "b4",
    buyerName: "Dian Saputra",
    partnerUserId: "u5",
    partnerName: "Pak Wayan",
    villageId: "v1",
    villageName: "Desa Penglipuran",
    splits: [
      { recipientType: "partner", recipientId: "u5", recipientName: "Pak Wayan", amount: 1700000, percentage: 85 },
      { recipientType: "platform", recipientId: "platform", recipientName: "Admin DeWi", amount: 300000, percentage: 15 },
    ],
    refund: {
      type: "full",
      amount: 2000000,
      reason: "Tamu membatalkan karena alasan kesehatan.",
      status: "processed",
      requestedAt: "2026-04-05T10:00:00Z",
      processedAt: "2026-04-06T14:00:00Z",
    },
    createdAt: "2026-03-28T09:00:00Z",
    updatedAt: "2026-04-06T14:00:00Z",
  },
  {
    id: "t5",
    orderId: "ORD-2026-0005",
    type: "facility_rental",
    status: "success",
    amount: 500000,
    currency: "IDR",
    platformFee: 75000,
    paymentMethod: "va_bni",
    paymentProvider: "midtrans",
    buyerUserId: "b5",
    buyerName: "PT Event Nusantara",
    partnerUserId: "v2-admin",
    partnerName: "Desa Wae Rebo",
    villageId: "v2",
    villageName: "Desa Wae Rebo",
    splits: [
      { recipientType: "village", recipientId: "v2", recipientName: "Desa Wae Rebo", amount: 425000, percentage: 85 },
      { recipientType: "platform", recipientId: "platform", recipientName: "Admin DeWi", amount: 75000, percentage: 15 },
    ],
    settlement: { status: "pending", schedule: "standard" },
    createdAt: "2026-04-10T16:00:00Z",
    updatedAt: "2026-04-10T16:00:00Z",
  },
  {
    id: "t6",
    orderId: "ORD-2026-0006",
    type: "sme_order",
    status: "failed",
    amount: 180000,
    currency: "IDR",
    platformFee: 18000,
    paymentMethod: "ewallet_ovo",
    paymentProvider: "xendit",
    buyerUserId: "b6",
    buyerName: "Lisa Permata",
    partnerUserId: "u6",
    partnerName: "Ibu Ketut",
    villageId: "v1",
    villageName: "Desa Penglipuran",
    splits: [
      { recipientType: "partner", recipientId: "u6", recipientName: "Ibu Ketut", amount: 162000, percentage: 90 },
      { recipientType: "platform", recipientId: "platform", recipientName: "Admin DeWi", amount: 18000, percentage: 10 },
    ],
    createdAt: "2026-04-09T20:00:00Z",
    updatedAt: "2026-04-09T20:30:00Z",
  },
];

// ============================================================
// MOCK AUDIT LOGS
// ============================================================
export const mockAuditLogs: AuditLog[] = [
  {
    id: "al1",
    timestamp: "2026-04-11T08:30:00Z",
    userId: "u1",
    userName: "Budi Santoso",
    userRole: "super_admin",
    action: "login",
    module: "dashboard",
    resourceType: "session",
    resourceId: "s-001",
    description: "Login berhasil dari Jakarta",
    metadata: { ip: "103.28.12.1", browser: "Chrome 124" },
    ipAddress: "103.28.12.1",
    userAgent: "Mozilla/5.0 Chrome/124.0",
    status: "success",
  },
  {
    id: "al2",
    timestamp: "2026-04-11T07:45:00Z",
    userId: "u2",
    userName: "Siti Rahayu",
    userRole: "admin",
    action: "approve",
    module: "approvals",
    resourceType: "approval",
    resourceId: "a4",
    description: "Approval partner registration: Pak Wayan (ACCOMMODATION)",
    metadata: { status: "approved", notes: "Semua dokumen lengkap" },
    ipAddress: "103.28.12.2",
    userAgent: "Mozilla/5.0 Firefox/123.0",
    status: "success",
  },
  {
    id: "al3",
    timestamp: "2026-04-11T06:00:00Z",
    userId: "u3",
    userName: "Ahmad Wijaya",
    userRole: "finance_admin",
    action: "export",
    module: "transactions",
    resourceType: "report",
    resourceId: "rpt-apr-2026",
    description: "Export transaksi bulan April 2026",
    metadata: { format: "excel", rows: 156 },
    ipAddress: "103.28.12.3",
    userAgent: "Mozilla/5.0 Chrome/124.0",
    status: "success",
  },
  {
    id: "al4",
    timestamp: "2026-04-10T23:00:00Z",
    userId: "unknown",
    userName: "Unknown",
    userRole: "viewer",
    action: "login",
    module: "dashboard",
    resourceType: "session",
    resourceId: "s-fail-001",
    description: "Login gagal: email tidak ditemukan (hacker@test.com)",
    metadata: { email: "hacker@test.com", attempts: 3 },
    ipAddress: "185.220.101.1",
    userAgent: "Mozilla/5.0 Bot",
    status: "failed",
  },
  {
    id: "al5",
    timestamp: "2026-04-10T15:30:00Z",
    userId: "u1",
    userName: "Budi Santoso",
    userRole: "super_admin",
    action: "update",
    module: "users",
    resourceType: "user",
    resourceId: "u8",
    description: "Mengubah status user Nyoman Adi → suspended",
    metadata: { before: { status: "active" }, after: { status: "suspended" } },
    ipAddress: "103.28.12.1",
    userAgent: "Mozilla/5.0 Chrome/124.0",
    status: "success",
  },
  {
    id: "al6",
    timestamp: "2026-04-10T14:00:00Z",
    userId: "u1",
    userName: "Budi Santoso",
    userRole: "super_admin",
    action: "settings_change",
    module: "settings",
    resourceType: "setting",
    resourceId: "feature-flags",
    description: "Mengaktifkan fitur: Experience Coordination",
    metadata: { key: "enableExperienceCoordination", before: false, after: true },
    ipAddress: "103.28.12.1",
    userAgent: "Mozilla/5.0 Chrome/124.0",
    status: "success",
  },
  {
    id: "al7",
    timestamp: "2026-04-10T10:00:00Z",
    userId: "u2",
    userName: "Siti Rahayu",
    userRole: "admin",
    action: "create",
    module: "villages",
    resourceType: "village",
    resourceId: "v4",
    description: "Menambahkan Desa Pentingsari",
    metadata: { villageName: "Desa Pentingsari", province: "DI Yogyakarta" },
    ipAddress: "103.28.12.2",
    userAgent: "Mozilla/5.0 Firefox/123.0",
    status: "success",
  },
  {
    id: "al8",
    timestamp: "2026-04-09T16:30:00Z",
    userId: "u3",
    userName: "Ahmad Wijaya",
    userRole: "finance_admin",
    action: "reject",
    module: "approvals",
    resourceType: "withdrawal",
    resourceId: "a5",
    description: "Menolak pencairan: Ibu Ketut — saldo minimum belum tercapai",
    metadata: { reason: "Saldo belum mencapai minimum pencairan" },
    ipAddress: "103.28.12.3",
    userAgent: "Mozilla/5.0 Chrome/124.0",
    status: "success",
  },
];

// ============================================================
// MOCK WEB CONTENT
// ============================================================
export const mockContents: WebContent[] = [
  {
    id: "c1",
    slug: "terms-and-conditions",
    title: "Syarat & Ketentuan",
    content: "<h1>Syarat dan Ketentuan Penggunaan Platform Desa Wisata</h1><p>Terakhir diperbarui: 1 April 2026</p><p>Dengan mengakses dan menggunakan platform ini...</p>",
    status: "published",
    version: 3,
    locale: "id",
    publishedAt: "2026-04-01T00:00:00Z",
    lastEditedBy: "u1",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2026-04-01T00:00:00Z",
  },
  {
    id: "c2",
    slug: "privacy-policy",
    title: "Kebijakan Privasi",
    content: "<h1>Kebijakan Privasi</h1><p>Platform Desa Wisata menghormati privasi pengguna...</p>",
    status: "published",
    version: 2,
    locale: "id",
    publishedAt: "2026-03-15T00:00:00Z",
    lastEditedBy: "u2",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2026-03-15T00:00:00Z",
  },
  {
    id: "c3",
    slug: "refund-policy",
    title: "Kebijakan Pengembalian Dana",
    content: "<h1>Kebijakan Refund</h1><p>Pengembalian dana dapat dilakukan dalam kondisi berikut...</p>",
    status: "published",
    version: 1,
    locale: "id",
    publishedAt: "2025-06-01T00:00:00Z",
    lastEditedBy: "u1",
    createdAt: "2025-06-01T00:00:00Z",
    updatedAt: "2025-06-01T00:00:00Z",
  },
  {
    id: "c4",
    slug: "faq",
    title: "FAQ",
    content: "<h1>Frequently Asked Questions</h1><h2>Bagaimana cara mendaftar sebagai partner?</h2><p>Anda dapat mendaftar melalui aplikasi Mitra DeWi...</p>",
    status: "draft",
    version: 1,
    locale: "id",
    lastEditedBy: "u2",
    createdAt: "2026-04-10T00:00:00Z",
    updatedAt: "2026-04-10T00:00:00Z",
  },
  {
    id: "c5",
    slug: "partner-guidelines",
    title: "Panduan Partner",
    content: "<h1>Panduan bagi Partner Desa Wisata</h1><p>Sebagai partner Desa Wisata, Anda bertanggung jawab untuk...</p>",
    status: "published",
    version: 2,
    locale: "id",
    publishedAt: "2026-02-01T00:00:00Z",
    lastEditedBy: "u2",
    createdAt: "2025-03-01T00:00:00Z",
    updatedAt: "2026-02-01T00:00:00Z",
  },
];

// ============================================================
// MOCK DASHBOARD DATA
// ============================================================
export const mockDashboardKpi = {
  totalUsers: 1234,
  activeUsers: 892,
  totalVillages: 56,
  activeVillages: 42,
  totalPartners: 312,
  pendingApprovals: 18,
  monthlyTransactions: 45600000,
  monthlyRevenue: 6840000,
};

export const mockUserGrowth = [
  { month: "Nov", value: 780 },
  { month: "Des", value: 890 },
  { month: "Jan", value: 950 },
  { month: "Feb", value: 1050 },
  { month: "Mar", value: 1150 },
  { month: "Apr", value: 1234 },
];

export const mockTransactionVolume = [
  { month: "Nov", accommodation: 120, sme: 85, experience: 45, facility: 12 },
  { month: "Des", accommodation: 180, sme: 110, experience: 65, facility: 18 },
  { month: "Jan", accommodation: 150, sme: 95, experience: 55, facility: 15 },
  { month: "Feb", accommodation: 165, sme: 100, experience: 60, facility: 20 },
  { month: "Mar", accommodation: 195, sme: 125, experience: 72, facility: 22 },
  { month: "Apr", accommodation: 210, sme: 140, experience: 80, facility: 25 },
];

export const mockRevenueByType = [
  { name: "Accommodation", value: 3420000, fill: "#3b82f6" },
  { name: "SME Order", value: 684000, fill: "#10b981" },
  { name: "Experience", value: 1710000, fill: "#f59e0b" },
  { name: "Facility", value: 1026000, fill: "#8b5cf6" },
];

export const mockVillagePerformance = [
  { name: "Penglipuran", revenue: 45600000 },
  { name: "Nglanggeran", revenue: 35000000 },
  { name: "Wae Rebo", revenue: 28000000 },
  { name: "Pujon Kidul", revenue: 18000000 },
  { name: "Trunyan", revenue: 12000000 },
];
