import type { HomepageAdvertisementRequest } from "./types";

export const HOMEPAGE_AD_REQUESTS: HomepageAdvertisementRequest[] = [
  {
    id: "ad-001",
    role: "accommodation",
    campaignName: "Weekend Staycation Hemat",
    placement: "featured",
    requestedBy: "Hotel Bukit Hijau",
    requestedAt: "2026-05-01",
    status: "pending",
    note: "Menunggu review Super Admin",
  },
  {
    id: "ad-002",
    role: "sme",
    campaignName: "Paket Oleh-oleh Premium",
    placement: "sidebar",
    requestedBy: "UMKM Batik Nusantara",
    requestedAt: "2026-04-28",
    status: "approved",
    note: "Aktif hingga 31 Mei",
  },
  {
    id: "ad-003",
    role: "experience",
    campaignName: "Festival Kopi Desa 2026",
    placement: "hero",
    requestedBy: "Nusantara Events",
    requestedAt: "2026-05-02",
    status: "pending",
  },
  {
    id: "ad-004",
    role: "transport",
    campaignName: "Shuttle Wisata Pagi",
    placement: "featured",
    requestedBy: "Sejahtera Transport",
    requestedAt: "2026-04-22",
    status: "rejected",
    note: "Visual banner belum sesuai panduan brand",
  },
  {
    id: "ad-005",
    role: "village",
    campaignName: "Paket Jelajah Desa 3D2N",
    placement: "hero",
    requestedBy: "Pengelola Desa Sari Alam",
    requestedAt: "2026-04-30",
    status: "approved",
    note: "Tayang di homepage minggu ini",
  },
];
